apiVersion: skaffold/v2beta18
kind: Config
metadata:
  name: ticketshop
build:
  artifacts:
  - image: ticketshop/auth
    context: auth
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - infra/k8s/auth-depl.yaml
    - infra/k8s/ingress-srv.yaml